config/routes.rb
Railsblog::Application.routes.draw do

  resources :comments

  resources :posts

  root 'users#index'

  resources :users

  resources :sessions

  resources :posts do
    resources :comments
  end  

  delete '/logout' => 'sessions#destroy'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
   belongs_to :post
   belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
   belongs_to :user
   has_many :comments
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
   has_many :posts
   has_many :comments
   validates :password, presence: true,
   confirmation: true
   validates_confirmation_of :password 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include ApplicationHelper
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

   def create
      # @comment = Comment.new(comment_params)
      @comment = current_user.comments.create(params[:comment])
      redirect_to request.env['HTTP_REFERER']
   end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

   def index
      @posts = Post.all
      @post = Post.new
      @comment = Comment.new
   end   

   def new
      @post = Post.new
   end

   def create
      
      @user = current_user
      @comment = current_user.comments.create(params[:comment])
      @post = current_user.posts.create params[:post]
      flash[:alert] = "Just created your post!"
      redirect_to posts_path

   end

   def show
      @post = Post.find params[:id]
      @comment = Comment.new
      
   end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def destroy
    log_out
    flash[:alert] = "Successfully Logged Out"
    redirect_to root_path
  end

  def create
    username = params[:username]
    password = params[:password]


    @user = User.where(username: username).first

    if @user.nil?
      #wrong username case
      flash[:alert] = "Incorrect credentials"
      redirect_to root_path
    else
      if @user.password == password
        session[:user_id] = @user.id
        flash[:alert] = "Welcome #{current_user.username}!"
        redirect_to root_path
      else
        #wrong password case
        flash[:alert] = "Incorrect credentials"
        redirect_to root_path
      end
    end

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   
   def index
      @user = User.all
   end



   def new 
    @user = User.new
   end   

   def create
         @user = User.new
           params[:user][:password] == params[:password_confirmation]
           @user = User.create params[:user]
           flash[:alert] = "#{@user.username} has been signed up"
           redirect_to users_path
        
   end

   def show
      @user= User.find params[:id]
      @post = Post.all
   end

   
   def edit
      @user = User.find params[:id]
   end


   def update
    @user = User.find params[:id]
    @up = user_params
      if user_params[:password].blank?
       @up.delete(:password)
       @up.delete(:password_confirmation)
      end
      @user.update! @up 
      flash[:notice] = "Profile updated"
      redirect_to user_path(@user)
      
   end

   def destroy
    @user = User.find params[:id]
    @user.destroy!
    session.clear
    flash[:success] = "User deleted"
    redirect_to root_path
  end

  def user_params
    params.require(:user).permit(:fname, :lname, :password, :password_confirmation, :age, :location )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    if session[:user_id]
      @current_user = User.find session[:user_id]
    end
  end
   def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<!-- <link href='http://fonts.googleapis.com/css?family=Indie+Flower' rel='stylesheet' type='text/css'> -->
  <title>Railsblog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<div id = "wrapper">
<nav>
    <ul>
          
        <% if current_user %>
           
          <li> <%= link_to "Home", root_path %> </li>  
          <li> <%= link_to "Profile", user_path(current_user)%> </li> 
          <li><%= link_to "Feed", posts_path%></li>
          <li><%= link_to "Sign Out", logout_path, method: :delete %></li>
        
        <% else %>

        <div class="form_inputbutton">
        <li> <%= link_to "Sign Up", new_user_path %> </li> 
        </div>
            <div class="small_form">
            <%= form_tag '/sessions' do %>
            <%= text_field_tag( :username, nil, placeholder: "Username", :class => "form_inputbox" ) %>
            <%= password_field_tag :password, nil, placeholder: "Password", :class => "form_inputbox" %>
                 <%= submit_tag("Log In", class: "loggin") %> 
            </div>
             <% end %>
             <% end %>
         
       
     </ul>
        
    <br><br>
</nav>

        <% if flash[:alert] %>
          <div class="flash" >
            <%= flash[:alert] %>
          </div>
        <% end %>
<div class = "clear"></div>


<%= yield %>
</div>


</body>
</html>

app/views/posts/index.html.erb
<div class = "Container">

  <div class="content">
    <h1> Post Index Page </h1>
    <h4>(For more use the scroll)</h4>

    <div class= "newpost">
  <%= form_for @post do |f| %>
  <%= f.label :Title %>
  <%= f.text_field :posttitle, {placeholder: 'Title'} %> <br>
  <%= f.label :Text %>
  <%= f.text_field :posttext, {placeholder: 'Enter your post'} %> <br>
  <%= f.submit :Create %>
  <% end %>
</div>
<div class="postscroll">
  <% @posts.reverse.each do |post| %>

    <div class = "posttitle"> 
      <h2> <%=link_to post.posttitle, post_path(post.id)%> </h2>
    </div>

    <div class = "posttext">
    <h2> <%=post.posttext%> </h2>
    </div>

    <div class= "comment">
  <%= form_for @comment do |f| %>
    <h3> <%= f.label :Comment %> </h3>

    <%= f.text_field :commenttext %>
    <%= f.hidden_field :post_id, value: post.id %>
    <%= f.submit :create %>
    <br><br>
    <% end %>
    </div>
    <div class="commentout">
    <% post.comments.each do |c| %>
       <p> <%=c.commenttext%> </p>
    <% end %>
    <hr>
  </div>
  <% end %>   
</div>

   
   
  </div> <!-- end of content-->
</div> <!-- end of container -->

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
  <%= f.label :Title %>
  <%= f.text_field :posttitle, {placeholder: 'Title'} %> <br>
  <%= f.label :Text %>
  <%= f.text_field :posttext, {placeholder: 'Enter your post'} %> <br>
  <%= f.submit :Create %>
<% end %>

app/views/posts/show.html.erb
<div class = "clear"></div>
<div id = "new_comment">
    <div class = "posttitle"> 
      <h1> <%=@post.posttitle %>  </h1>
    </div>
    
   <div class = "posttext">
      <h5> <%=@post.posttext%> </h5>
   </div>

<p>  Posted by <%=@post.user.username %>  <%=@post.created_at %> </p>

 <%= form_for @comment do |f| %>
    <h3> <%= f.label :Comment %> </h3>
    <%= f.text_field :commenttext, placeholder: 'Put comment here' %>
    <%= f.hidden_field :post_id, value: @post.id %>
    <%= f.submit :create %>
    <br><br>
    <% end %>


   <% @post.comments.each do |c| %>
       <p>User:  <%= c.user.username %> </p>  
         <p>Comment: <%=c.commenttext%> </p>
   <% end %>
</div>   

app/views/users/edit.html.erb
<div class="new_user">
  <h2> Editing User</h2>
  
  <div class= "new_form">

<table>
  <tr>
    <%= form_for @user do |f| %>
    <td><%= f.label :username %></td>
    <td><%= f.text_field :username, {placeholder: 'Username'} %> </td>
  </tr>
  <tr>
    <td><%= f.label :password %></td>
    <td><%= f.password_field :password, {placeholder: 'Password'} %> </td>
  </tr>
  <tr>
    <td><%= f.label :Confirm %></td>
    <td> <%= password_field_tag( :password_confirmation,nil, placeholder: "Password Confirmation") %> 
  </tr>
    <td><%= f.label :fname %></td>
    <td><%= f.text_field :fname, {placeholder: 'First Name'} %></td> 
  <tr>
  <td><%= f.label :lname %></td>
  <td><%= f.text_field :lname, {placeholder: 'Last Name'} %></td> 
  </tr>
  <td><%= f.label :age %></td>
  <td><%= text_field_tag :age, nil, {placeholder: 'Years old'} %></td> 
  <tr>
  <td><%= f.label :location %></td>
  <td><%= f.text_field :location, {placeholder: 'Location'} %> </td>
  </tr>
  <tr>
  <td><%= f.submit :Submit%></td>
  </tr>
  <% end %>
  </table>
  </<br>
  </div>
  <div class="setting">
  <%= link_to 'Back', user_path %><br>
    <% if current_user[:id]%>
      <%=link_to 'Delete', @user, method: :delete, data: {confirm: "You sure?"} %>
    <% end %>
  </div>
  
</div>

app/views/users/index.html.erb
<div class = "body_image">
   <div class = "Main Content">
     <div class = "allusers">
    <h2>Listing Users</h2>
    
  
          <% @user.each do |u| %>
      <div class = "online_circle">
            <p> <%= link_to u.username, users_path %> </p>
       </div>     
          <% end %> 
     
    </div>
     <img src = "../tahta.png"> </img>

   </div> <!-- end of main content-->
</div> <!-- end of body image -->

app/views/users/new.html.erb
<div class="new_user">
  <h2> Insert your information please</h2>
  <div class= "new_form">

  <table>
  <tr>
    <%= form_for @user do |f| %>
    <td><%= f.label :username %></td>
    <td><%= f.text_field :username, {placeholder: 'Username'} %> </td>
  </tr>
  <tr>
    <td><%= f.label :password %></td>
    <td><%= f.password_field :password, {placeholder: 'Password'} %> </td>
  </tr>
  <tr>
    <td><%= f.label :Confirm %></td>
    <td> <%= password_field_tag( :password_confirmation,nil, placeholder: "Password Confirmation") %> 
  </tr>
    <td><%= f.label :fname %></td>
    <td><%= f.text_field :fname, {placeholder: 'First Name'} %></td> 
  <tr>
  <td><%= f.label :lname %></td>
  <td><%= f.text_field :lname, {placeholder: 'Last Name'} %></td> 
  </tr>
  <td><%= f.label :age %></td>
  <td><%= text_field_tag :age, nil, {placeholder: 'Years old'} %></td> 
  <tr>
  <td><%= f.label :location %></td>
  <td><%= f.text_field :location, {placeholder: 'Location'} %> </td>
  </tr>
  <tr>
  <td><%= f.submit :Submit%></td>
  </tr>
  <% end %>
  </table>
  </div>
</div>

app/views/users/show.html.erb
<div class = "new_user">
   
<div id = "profile_info">
   <div class = "user_name">
   <h3>
      <%= @user.fname%>
      <%= @user.lname%>
   </h3>
   </div>  

   <div class = "user_username">
      Username: 
     <%= @user.username %> 
   </div> 

   <br>

   <div class = "user_location">
      Location:
      <%= @user.location%>
   </div>

   <div class = "user_birthday">
     
      <%= @user.birthday%>
   </div>      
</div>
</div> 
<br>
<div id="recpost">
   <p>Recent Posts: </p>
   <div class="show_post">
      <% @user.posts.each do |p| %>
         <%= link_to p.posttitle, posts_path %>
      <%end%>
   </div><br>
   <div class="setting">
      <%= link_to 'Edit', edit_user_path(current_user)%>
      <% if current_user[:id]%>
         <%=link_to 'Delete Account', @user, method: :delete, data: {confirm: "You sure?"} %>
      <% end %>
   </div>
</div>
 